EMV_TAGS = {
    0x42: {"name": "Issuer Identification Number", "format": "n", "length": 6},
    0x4F: {"name": "Application Identifier (AID) - card", "format": "b", "length": None},
    0x50: {"name": "Application Label", "format": "ans", "length": None},
    0x57: {"name": "Track 2 Equivalent Data", "format": "b", "length": None},
    0x5A: {"name": "Application Primary Account Number (PAN)", "format": "cn", "length": None},
    0x5F20: {"name": "Cardholder Name", "format": "ans", "length": 26},
    0x5F24: {"name": "Application Expiration Date", "format": "n", "length": 3},
    0x5F25: {"name": "Application Effective Date", "format": "n", "length": 3},
    0x5F28: {"name": "Issuer Country Code", "format": "n", "length": 2},
    0x5F2A: {"name": "Transaction Currency Code", "format": "n", "length": 2},
    0x5F2D: {"name": "Language Preference", "format": "ans", "length": None},
    0x5F30: {"name": "Service Code", "format": "n", "length": 2},
    0x5F34: {"name": "Application PAN Sequence Number", "format": "n", "length": 1},
    0x5F36: {"name": "Transaction Currency Exponent", "format": "n", "length": 1},
    0x5F50: {"name": "Issuer URL", "format": "ans", "length": None},
    0x5F53: {"name": "International Bank Account Number (IBAN)", "format": "b", "length": None},
    0x5F54: {"name": "Bank Identifier Code (BIC)", "format": "b", "length": None},
    0x61: {"name": "Application Template", "format": "b", "constructed": True},
    0x6F: {"name": "File Control Information (FCI) Template", "format": "b", "constructed": True},
    0x70: {"name": "READ RECORD Response Message Template", "format": "b", "constructed": True},
    0x71: {"name": "Issuer Script Template 1", "format": "b", "constructed": True},
    0x72: {"name": "Issuer Script Template 2", "format": "b", "constructed": True},
    0x77: {"name": "Response Message Template Format 2", "format": "b", "constructed": True},
    0x80: {"name": "Response Message Template Format 1", "format": "b"},
    0x82: {"name": "Application Interchange Profile", "format": "b", "length": 2},
    0x83: {"name": "Command Template", "format": "b"},
    0x84: {"name": "Dedicated File (DF) Name", "format": "b", "length": None},
    0x86: {"name": "Issuer Script Command", "format": "b"},
    0x87: {"name": "Application Priority Indicator", "format": "b", "length": 1},
    0x88: {"name": "Short File Identifier (SFI)", "format": "b", "length": 1},
    0x89: {"name": "Authorization Code", "format": "an", "length": 6},
    0x8A: {"name": "Authorization Response Code", "format": "an", "length": 2},
    0x8C: {"name": "Card Risk Management Data Object List 1 (CDOL1)", "format": "b"},
    0x8D: {"name": "Card Risk Management Data Object List 2 (CDOL2)", "format": "b"},
    0x8E: {"name": "Cardholder Verification Method (CVM) List", "format": "b"},
    0x8F: {"name": "Certification Authority Public Key Index", "format": "b", "length": 1},
    0x90: {"name": "Issuer Public Key Certificate", "format": "b"},
    0x91: {"name": "Issuer Authentication Data", "format": "b", "length": None},
    0x92: {"name": "Issuer Public Key Remainder", "format": "b"},
    0x93: {"name": "Signed Static Application Data", "format": "b"},
    0x94: {"name": "Application File Locator (AFL)", "format": "b"},
    0x95: {"name": "Terminal Verification Results", "format": "b", "length": 5},
    0x97: {"name": "Transaction Certificate Data Object List (TDOL)", "format": "b"},
    0x98: {"name": "Transaction Certificate (TC) Hash Value", "format": "b", "length": 20},
    0x99: {"name": "Transaction Personal Identification Number (PIN) Data", "format": "b"},
    0x9A: {"name": "Transaction Date", "format": "n", "length": 3},
    0x9B: {"name": "Transaction Status Information", "format": "b", "length": 2},
    0x9C: {"name": "Transaction Type", "format": "n", "length": 1},
    0x9D: {"name": "Directory Definition File (DDF) Name", "format": "b"},
    0x9F01: {"name": "Acquirer Identifier", "format": "n", "length": 6},
    0x9F02: {"name": "Amount, Authorized (Numeric)", "format": "n", "length": 6},
    0x9F03: {"name": "Amount, Other (Numeric)", "format": "n", "length": 6},
    0x9F04: {"name": "Amount, Other (Binary)", "format": "b", "length": 4},
    0x9F05: {"name": "Application Discretionary Data", "format": "b"},
    0x9F06: {"name": "Application Identifier (AID) - terminal", "format": "b"},
    0x9F07: {"name": "Application Usage Control", "format": "b", "length": 2},
    0x9F08: {"name": "Application Version Number (card)", "format": "b", "length": 2},
    0x9F09: {"name": "Application Version Number (terminal)", "format": "b", "length": 2},
    0x9F0B: {"name": "Cardholder Name Extended", "format": "ans"},
    0x9F0D: {"name": "Issuer Action Code - Default", "format": "b", "length": 5},
    0x9F0E: {"name": "Issuer Action Code - Denial", "format": "b", "length": 5},
    0x9F0F: {"name": "Issuer Action Code - Online", "format": "b", "length": 5},
    0x9F10: {"name": "Issuer Application Data", "format": "b"},
    0x9F11: {"name": "Issuer Code Table Index", "format": "n", "length": 1},
    0x9F12: {"name": "Application Preferred Name", "format": "ans"},
    0x9F13: {"name": "Last Online Application Transaction Counter (ATC) Register", "format": "b", "length": 2},
    0x9F14: {"name": "Lower Consecutive Offline Limit", "format": "b", "length": 1},
    0x9F15: {"name": "Merchant Category Code", "format": "n", "length": 2},
    0x9F16: {"name": "Merchant Identifier", "format": "ans", "length": 15},
    0x9F17: {"name": "Personal Identification Number (PIN) Try Counter", "format": "b", "length": 1},
    0x9F18: {"name": "Issuer Script Identifier", "format": "b", "length": 4},
    0x9F1A: {"name": "Terminal Country Code", "format": "n", "length": 2},
    0x9F1B: {"name": "Terminal Floor Limit", "format": "b", "length": 4},
    0x9F1C: {"name": "Terminal Identification", "format": "an", "length": 8},
    0x9F1D: {"name": "Terminal Risk Management Data", "format": "b"},
    0x9F1E: {"name": "Interface Device (IFD) Serial Number", "format": "an", "length": 8},
    0x9F1F: {"name": "Track 1 Discretionary Data", "format": "ans"},
    0x9F20: {"name": "Track 2 Discretionary Data", "format": "an"},
    0x9F21: {"name": "Transaction Time", "format": "n", "length": 3},
    0x9F22: {"name": "Certification Authority Public Key Index", "format": "b", "length": 1},
    0x9F23: {"name": "Upper Consecutive Offline Limit", "format": "b", "length": 1},
    0x9F26: {"name": "Application Cryptogram (ARQC/TC/AAC)", "format": "b", "length": 8},
    0x9F27: {"name": "Cryptogram Information Data", "format": "b", "length": 1},
    0x9F28: {"name": "ICC Dynamic Number (IDN)", "format": "b"},
    0x9F29: {"name": "Terminal Type", "format": "b", "length": 1},
    0x9F2A: {"name": "Kernel Identifier", "format": "b"},
    0x9F2D: {"name": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate", "format": "b"},
    0x9F2E: {"name": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent", "format": "b"},
    0x9F2F: {"name": "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder", "format": "b"},
    0x9F32: {"name": "Issuer Public Key Exponent", "format": "b"},
    0x9F33: {"name": "Terminal Capabilities", "format": "b", "length": 3},
    0x9F34: {"name": "Cardholder Verification Method (CVM) Results", "format": "b", "length": 3},
    0x9F35: {"name": "Terminal Type", "format": "b", "length": 1},
    0x9F36: {"name": "Application Transaction Counter (ATC)", "format": "b", "length": 2},
    0x9F37: {"name": "Unpredictable Number", "format": "b", "length": 4},
    0x9F38: {"name": "Processing Options Data Object List (PDOL)", "format": "b"},
    0x9F39: {"name": "Point-of-Service (POS) Entry Mode", "format": "n", "length": 1},
    0x9F3A: {"name": "Amount, Reference Currency", "format": "b", "length": 4},
    0x9F3B: {"name": "Application Reference Currency", "format": "n"},
    0x9F3C: {"name": "Transaction Reference Currency Code", "format": "n", "length": 2},
    0x9F3D: {"name": "Transaction Reference Currency Exponent", "format": "n", "length": 1},
    0x9F40: {"name": "Additional Terminal Capabilities", "format": "b", "length": 5},
    0x9F41: {"name": "Transaction Sequence Counter", "format": "n", "length": 4},
    0x9F42: {"name": "Application Currency Code", "format": "n", "length": 2},
    0x9F43: {"name": "Application Reference Currency Exponent", "format": "n", "length": 1},
    0x9F44: {"name": "Application Currency Exponent", "format": "n", "length": 1},
    0x9F45: {"name": "Data Authentication Code", "format": "b", "length": 2},
    0x9F46: {"name": "Integrated Circuit Card (ICC) Public Key Certificate", "format": "b"},
    0x9F47: {"name": "Integrated Circuit Card (ICC) Public Key Exponent", "format": "b"},
    0x9F48: {"name": "Integrated Circuit Card (ICC) Public Key Remainder", "format": "b"},
    0x9F49: {"name": "Dynamic Data Authentication Data Object List (DDOL)", "format": "b"},
    0x9F4A: {"name": "Static Data Authentication Tag List", "format": "b"},
    0x9F4B: {"name": "Signed Dynamic Application Data", "format": "b"},
    0x9F4C: {"name": "ICC Dynamic Number", "format": "b", "length": 8},
    0x9F4D: {"name": "Log Entry", "format": "b", "length": 2},
    0x9F4E: {"name": "Merchant Name and Location", "format": "ans"},
    0x9F4F: {"name": "Log Format", "format": "b"},
    0x9F51: {"name": "Application Currency Code", "format": "n"},
    0x9F52: {"name": "Card Verification Results", "format": "b"},
    0x9F53: {"name": "Consecutive Transaction Limit (International - Country)", "format": "b"},
    0x9F54: {"name": "Cumulative Total Transaction Amount Limit", "format": "b"},
    0x9F55: {"name": "Geographic Indicator", "format": "b"},
    0x9F56: {"name": "Issuer Authentication Indicator", "format": "b"},
    0x9F57: {"name": "Issuer Country Code", "format": "n"},
    0x9F58: {"name": "Lower Consecutive Offline Limit (Card Check)", "format": "b"},
    0x9F59: {"name": "Upper Consecutive Offline Limit (Card Check)", "format": "b"},
    0x9F5A: {"name": "Issuer URL2", "format": "b"},
    0x9F5C: {"name": "Upper Cumulative Domestic Offline Transaction Amount", "format": "b"},
    0x9F72: {"name": "Consecutive Transaction Limit (International)", "format": "b"},
    0x9F74: {"name": "VLP Issuer Authorisation Code", "format": "b"},
    0x9F75: {"name": "Cumulative Domestic Cash Amount Upper Limit", "format": "b"},
    0x9F76: {"name": "Secondary Application Currency Code", "format": "b"},
    0x9F77: {"name": "VLP Available Funds", "format": "b"},
    0x9F78: {"name": "VLP Single Transaction Limit", "format": "b"},
    0x9F79: {"name": "VLP Balance", "format": "b"},
    0xA5: {"name": "File Control Information (FCI) Proprietary Template", "format": "b", "constructed": True},
    0xBF0C: {"name": "File Control Information (FCI) Issuer Discretionary Data", "format": "b", "constructed": True},
}

CRYPTOGRAM_TYPE = {
    0x00: "AAC",
    0x40: "TC",
    0x80: "ARQC",
}

TRANSACTION_TYPES = {
    0x00: "Purchase",
    0x01: "Cash Advance",
    0x09: "Purchase with Cashback",
    0x10: "Account Funding",
    0x11: "Quasi-Cash",
    0x20: "Refund",
    0x21: "Account Verification",
    0x22: "Balance Inquiry",
    0x28: "Payment",
    0x30: "Top-up",
    0x31: "Prepaid Activation",
    0x40: "Cash Disbursement",
}

TERMINAL_TYPES = {
    0x11: "Attended offline-only (financial institution)",
    0x12: "Attended offline with online capability (financial institution)",
    0x13: "Attended online only (financial institution)",
    0x14: "Attended offline-only (merchant)",
    0x15: "Attended offline with online capability (merchant)",
    0x16: "Attended online only (merchant)",
    0x21: "Unattended offline-only (financial institution)",
    0x22: "Unattended offline with online capability (financial institution)",
    0x23: "Unattended online only (financial institution)",
    0x24: "Unattended offline-only (merchant)",
    0x25: "Unattended offline with online capability (merchant)",
    0x26: "Unattended online only (merchant)",
    0x34: "Unattended card acceptor (cardholder-operated, merchant)",
    0x35: "Unattended card acceptor (cardholder-operated, merchant) online",
    0x36: "Unattended card acceptor (cardholder-operated, merchant) online only",
}
